abstract: Test for valid YAML
author: Jonathan Rockway <jrockway@cpan.org
build_requires: 
  Directory::Scratch: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: Perl
name: Test-YAML-Valid
no_index: 
  directory: 
    - inc
    - t
requires: 
  Exporter: 0
  Test::Builder: 0
  YAML: 0
version: 0.01
